services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-expense_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-expense_pass}
      POSTGRES_DB: ${POSTGRES_DB:-expense_db}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - expense-tracker

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://db:5432/expense_db}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-expense_user}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-expense_pass}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO:-update}
      - JWT_SECRET=${JWT_SECRET:-MySecretKeyForJWTTokenGenerationExpenseTrackerApp2024SecureKey}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME:-dxufhhhbl}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY:-724977371973365}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET:-D9pmAVN1e1OooB-vkkyxoJ00OHI}
      - MAIL_HOST=${MAIL_HOST:-smtp.gmail.com}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USERNAME=${MAIL_USERNAME:-niyokwizerajd123@gmail.com}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-fxywzvflonokevkx }
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:4000}
    ports:
      - "8080:8080"
    networks:
      - expense-tracker

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "4000:4000"
    networks:
      - expense-tracker

volumes:
  db-data:

networks:
  expense-tracker:
    name: expense-tracker
